### ISSUE TITLE
No work, help me pls

### ISSUE THREAD

**Issue by elaliaslocoxd** [xbinner18/Mrbannker#6]
I already changed the proxies and the bot still doesn't work, make a video tutorial please

**Comment by xbinner18** [comment]
https://github.com/elaliaslocoxd/Mrbannke/blob/52d14ee243c0c49426bf903db53d4d309326d9fe/bot.py#L42 where is coma

**Comment by elaliaslocoxd** [comment]
thanks, it worked for me, can't you add more doors? And if it is possible, how do I do it?
